In [ ]:
import numpy as np

In [ ]:
def tridiagonal_solver(A, b, diag=False):
    n = len(b)
    # Параметры для метода прогонки
    alpha = np.zeros(n-1)  # Коэффициенты для поддиагонали
    beta = np.zeros(n)      # Диагональные элементы
    gamma = np.zeros(n-1)   # Коэффициенты для наддиагонали

    # Заполнение коэффициентов
    for i in range(n):
        if i > 0:
            alpha[i-1] = A[i, i-1]
        beta[i] = A[i, i]
        if i < n-1:
            gamma[i] = A[i, i+1]

    # Прямой ход
    for i in range(1, n):
        scale = alpha[i-1] / beta[i-1]
        beta[i] -= scale * gamma[i-1]
        b[i] -= scale * b[i-1]

    # Обратный ход
    x = np.zeros(n)
    x[-1] = b[-1] / beta[-1]
    for i in range(n-2, -1, -1):
        x[i] = (b[i] - gamma[i] * x[i+1]) / beta[i]

    if diag:
        return beta
    else:
        return x

def determinant(A):
    """Вычисляет определитель трёхдиагональной матрицы."""
    modified_diagonals = tridiagonal_solver(A, np.zeros(A.shape[0]), diag=True)
    det = np.prod(modified_diagonals)
    return det

def inverse_tridiagonal(A):
    """Находит обратную трёхдиагональную матрицу."""
    n = A.shape[0]
    A_inv = np.zeros((n, n))

    for i in range(n):
        e = np.zeros(n)
        e[i] = 1  # Столбец единичной матрицы
        A_inv[:, i] = tridiagonal_solver(A, e)

    return A_inv

def residual(A, x, b):
    """Вычисляет невязку r = Ax - b."""
    return A @ x - b

def condition_number(A):
    """Вычисляет число обусловленности v(A)."""
    A_inv = inverse_tridiagonal(A)
    return np.linalg.norm(A) * np.linalg.norm(A_inv)

In [ ]:
tridiagonal_solver(A, b)

array([ 4.75893861, -5.27935844, -6.23557948, -0.88508827,  4.20719919])

In [ ]:
r = A @ tridiagonal_solver(A, b) - b

In [ ]:
np.linalg.norm(r)

1.2731469178346864

In [ ]:
b

array([ 4.2326    , -3.32561354, -5.71924911, -0.10551814,  3.22644286])

In [ ]:
import numpy as np

def gauss_elimination(A, b):
    n = len(b)
    for i in range(n):
        for j in range(i + 1, n):
            if A[j, i] != 0:
                ratio = A[j, i] / A[i, i]
                A[j, i:] -= ratio * A[i, i:]
                b[j] -= ratio * b[i]
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i + 1:], x[i + 1:])) / A[i, i]

    return x

In [ ]:
gauss_elimination(A,b)

array([ 4.75893861, -3.93967789, -8.2232507 , -3.77070855,  3.97086151])

In [ ]:
np.linalg.solve(A, b)

array([ 4.75893861, -4.83279826, -6.96902066, -1.76437325,  4.15674223])